### ISSUE TITLE
md-card width problem

### ISSUE THREAD

**Issue by Clouard-Dista** [alexandrainst/node-red-contrib-ui-upload#11] opened 2022-06-13 09:57 UTC
Hello, My page is 14 wide but the ui-ipload md-card takes all the width and not only the desired one.
![image](https://user-images.githubusercontent.com/7159848/173327209-f788ae9e-0b06-4bec-8f9f-ecfed1e4c12d.png)

**Comment by Alkarex** [comment] 2022-12-15 09:55
If you are still around, attempt of fix in https://github.com/alexandrainst/node-red-contrib-ui-upload/pull/13
Tests welcome
Duplicate of https://github.com/alexandrainst/node-red-contrib-ui-upload/issues/5

**Closed by Alkarex** 2022-12-15 09:55 UTC
